# -*- coding: utf-8 -*-
"""Copy of Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fh6g24ugquGBzsPU1IxmeaE4sg8byW5B
"""

import numpy as np
import pandas as pd
import os

df_train = pd.read_csv('/content/fraudTrain.csv')

# Loading the testting data
df_test = pd.read_csv('/content/fraudTest.csv')

df_train

df_test

print(f"\nShape of Training Data: {df_train.shape}")
print(f"Shape of Testing Data:  {df_test.shape}")

print("\n--- First 5 Rows of Training Data ---")
display(df_train.head())

print("\n--- Data Info (Types & Missing Values) ---")
df_train.info()

duplicates = df_train.duplicated().sum()
print(f"\n--- Duplicate Rows: {duplicates} ---")

print("\n--- Unique Values per Column ---")
print(df_train.nunique())

columns_to_drop = ['Unnamed: 0', 'trans_num']

df_train = df_train.drop(columns=columns_to_drop, errors='ignore')
df_test = df_test.drop(columns=columns_to_drop, errors='ignore')

print(f"New Shape of Training Data: {df_train.shape}")

df_train['trans_date_trans_time'] = pd.to_datetime(df_train['trans_date_trans_time'])
df_train['dob'] = pd.to_datetime(df_train['dob'])

df_train['age'] = (df_train['trans_date_trans_time'] - df_train['dob']).dt.days // 365

# B. Extracting hours,weekdays,days,month and year
df_train['hour'] = df_train['trans_date_trans_time'].dt.hour
df_train['weekday'] = df_train['trans_date_trans_time'].dt.weekday
df_train['day'] = df_train['trans_date_trans_time'].dt.day
df_train['month'] = df_train['trans_date_trans_time'].dt.month

display(df_train.head())

import matplotlib.pyplot as plt
import seaborn as sns


categorical_cols = ['category', 'gender', 'state', 'job']

plt.figure(figsize=(18, 12))
plt.suptitle('Profile of Fraudulent Transactions (Categorical Insights)', fontsize=16)

# 4. Loop through columns and create plots
for i, col in enumerate(categorical_cols):
    plt.subplot(2, 2, i + 1)
    top_counts = df_train[col].value_counts().nlargest(5).index

    # Create Bar Plot
    sns.countplot(y=col, data=df_train,hue='is_fraud',order=top_counts,palette='magma')

    plt.title(f'Top 10 {col.title()}s for Fraud', fontsize=14)
    plt.xlabel('Number of Fraudulent Transactions')
    plt.ylabel(col.title())

plt.tight_layout()
plt.show()

numerical_cols = ['amt', 'age', 'city_pop', 'hour','weekday']

plt.figure(figsize=(16, 12))

# Loop through the columns and create a plot for each
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 3, i + 1)

    # Use a Box Plot to compare distributions
    # This shows the Median (middle line) and Outliers (dots)
    sns.boxplot( y=col, data=df_train, palette='coolwarm')

    plt.title(f'Numerical Variable distriubion: {col}', fontsize=14)
    plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

print("--- STATUS: Calculating Correlations... ---")

# 1. Selecting only numerical columns
numeric_df = df_train.select_dtypes(include=[np.number])

# 2. Calculating Correlation Matrix
corr_matrix = numeric_df.corr()
fraud_correlation = corr_matrix['is_fraud'].sort_values(ascending=False)
print("\n--- Top Features Correlated with Fraud ---")
print(fraud_correlation)

# VISUALIZATION: THE HEATMAP
plt.figure(figsize=(12, 10))
sns.heatmap(corr_matrix, cmap='coolwarm', annot=False, linewidths=0.5)
plt.title('Correlation Matrix of Numerical Features', fontsize=15)
plt.show()